services:
  # Backend API Service
  - type: web
    name: nutrack-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && cd backend && npm install
    startCommand: node backend/src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
    
  # Frontend Web Service
  - type: web
    name: nutrack
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: nutrack-api
          type: web
          property: host 